services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labweek05
      MYSQL_USER: p2n
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mariadb-cli:
    image: mariadb:latest
    container_name: mariadb-cli
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mariadb
    entrypoint: ["bash", "-c"]
    command: ["while true; do sleep 10; done"]

volumes:
  mariadb_data:
